include: jaffa_lints.yaml

analyzer: # TEMPORARY
  exclude:
    - example/old_lib/pages/**
    - example/old_lib/state/**
    - example/old_lib/main.dart

linter:
  rules:
    avoid_slow_async_io: false
