targets:
  $default:
    builders:
      drift_dev:
        enabled: false
      drift_dev:analyzer:
        enabled: true
        options: &options
          named_parameters: true
          store_date_time_values_as_text: true
      drift_dev:modular:
        enabled: true
        options: *options
