name: flutter_map_tile_caching
description: Plugin for 'flutter_map' providing advanced caching functionality,
  with ability to download map regions for offline use.
version: 10.1.1

repository: https://github.com/JaffaKetchup/flutter_map_tile_caching
issue_tracker: https://github.com/JaffaKetchup/flutter_map_tile_caching/issues
documentation: https://fmtc.jaffaketchup.dev

funding:
  - https://github.com/sponsors/JaffaKetchup

topics:
  - flutter-map
  - map
  - fmtc

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  async: ^2.13.0
  collection: ^1.19.1
  dart_earcut: ^1.2.0
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  flat_buffers: ^25.9.23 
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  http: ^1.6.0
  latlong2: ^0.9.1
  meta: ^1.17.0
  objectbox: ^5.2.0
  objectbox_flutter_libs: ^5.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3: ^2.7.5

dev_dependencies:
  build_runner: ^2.11.1
  drift_dev: ^2.31.0
  objectbox_generator: ^5.2.0
  pigeon_generator: ^3.1.1
  test: ^1.29.0

flutter: null

objectbox:
  output_dir: src/backend/impls/objectbox/native/models/generated

