blank_issues_enabled: false
contact_links:
  - name: Official Discord Server
    url: https://discord.gg/egEGeByf4q
    about: Need more generalised help, or just want to talk? Join the Discord server, which has a dedicated channel for plugins!
  - name: flutter_map Issues
    url: https://github.com/fleaflet/flutter_map/issues
    about: If your issue is due to a problem in 'flutter_map', please post your issue there instead
