name: Build Example Applications
on:
  workflow_run:
    workflows: ["Analyse Package & Contents"]
    types:
      - completed
  workflow_dispatch:

jobs:
  check-example-changes:
    name: "Check Example Application For Changes"
    runs-on: "ubuntu-20.04"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      example_changed: ${{ steps.check_file_changed.outputs.example_changed }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - shell: pwsh
        id: check_file_changed
        run: |
          $diff = git diff --name-only HEAD^ HEAD

          $SourceDiff = $diff | Where-Object { $_ -match '^example/'}
          $HasDiff = $SourceDiff.Length -gt 0

          Write-Host "::set-output name=example_changed::$HasDiff"

  build-example:
    name: "Build Example Applications"
    runs-on: windows-latest
    needs: [check-example-changes]
    if: needs.check-example-changes.outputs.example_changed == 'True'
    defaults:
      run:
        working-directory: ./example
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version
      - run: flutter clean
      - run: flutter build apk --split-per-abi --obfuscate --split-debug-info=/symbols
      - run: Remove-Item "prebuiltExampleApplications" -Recurse -ErrorAction Ignore
        working-directory: .
      - run: md prebuiltExampleApplications
        working-directory: .
      - run: move "example\build\app\outputs\flutter-apk\app-armeabi-v7a-release.apk" "prebuiltExampleApplications\AndroidApplication.apk"
        working-directory: .
      - run: flutter build windows --obfuscate --split-debug-info=/symbols
      - uses: vimtor/action-zip@v1
        with:
          files: ./example/build/windows/runner/Release
          dest: prebuiltExampleApplications/WindowsApplication.zip
      - uses: EndBug/add-and-commit@v9.0.1
        with:
          message: "Built Example Applications"
          add: "prebuiltExampleApplications/"
          default_author: github_actions
